# -- coding: utf-8 --
import pandas as pd
import numpy as np
def crimedata():
    data = pd.read_hdf('crime.h5')
    data = data[['OFFENSE_TYPE_ID','GEO_LAT', 'GEO_LON']]
    a= data[['GEO_LAT', 'GEO_LON']].apply(np.mean, axis=0)
    data3 = data.head(1000)
    x = data3.to_records(index=False)

    icons = {'traffic-accident-dui-duid': '0.png',
     'vehicular-eluding-no-chase': '1.png',
     'disturbing-the-peace': '2.png',
     'curfew': '3.png',
     'aggravated-assault': '4.png',
     'violation-of-restraining-order': '5.png',
     'assault-dv': '6.png',
     'criminal-mischief-mtr-veh': '7.png',
     'criminal-trespassing': '8.png',
     'traffic-accident-hit-and-run': '9.png',
     'traffic-accident': '10.png',
     'theft-from-bldg': '11.png',
     'theft-parts-from-vehicle': '12.png',
     'burglary-residence-no-force': '13.png',
     'drug-methampetamine-possess': '14.png',
     'theft-other': '15.png',
     'burglary-residence-by-force': '16.png',
     'theft-shoplift': '17.png',
     'theft-of-motor-vehicle': '18.png',
     'public-order-crimes-other': '19.png',
     'public-fighting': '20.png',
     'public-peace-other': '21.png',
     'criminal-mischief-other': '22.png',
     'traf-other': '23.png',
     'aggravated-assault-dv': '24.png',
     'theft-items-from-vehicle': '25.png',
     'weapon-poss-illegal-dangerous': '26.png',
     'police-interference': '27.png',
     'police-resisting-arrest': '28.png',
     'weapon-by-prev-offender-powpo': '29.png',
     'sex-aslt-rape': '30.png',
     'burglary-business-no-force': '31.png',
     'drug-poss-paraphernalia': '32.png',
     'criminal-mischief-graffiti': '33.png',
     'liquor-possession': '34.png',
     'robbery-residence': '35.png',
     'drug-pcs-other-drug': '36.png',
     'traf-vehicular-assault': '37.png',
     'traf-habitual-offender': '38.png',
     'drug-cocaine-possess': '39.png',
     'assault-simple': '40.png',
     'theft-of-services': '41.png',
     'threats-to-injure': '42.png',
     'drug-methampetamine-sell': '43.png',
     'drug-heroin-possess': '44.png',
     'contraband-into-prison': '45.png',
     'harassment': '46.png',
     'accessory-conspiracy-to-crime': '47.png',
     'police-false-information': '48.png',
     'theft-unauth-use-of-ftd': '49.png',
     'theft-bicycle': '50.png',
     'weapon-carrying-prohibited': '51.png',
     'menacing-felony-w-weap': '52.png',
     'littering': '53.png',
     'weapon-unlawful-discharge-of': '54.png',
     'weapon-carrying-concealed': '55.png',
     'robbery-street': '56.png',
     'agg-aslt-police-weapon': '57.png',
     'fraud-identity-theft': '58.png',
     'drug-opium-or-deriv-possess': '59.png',
     'weapon-altering-serial-number': '60.png',
     'robbery-business': '61.png',
     'burglary-business-by-force': '62.png',
     'theft-pick-pocket': '63.png',
     'burg-auto-theft-resd-w-force': '64.png',
     'drug-cocaine-sell': '65.png',
     'violation-of-court-order': '66.png',
     'weapon-other-viol': '67.png',
     'arson-other': '68.png',
     'kidnap-dv': '69.png',
     'reckless-endangerment': '70.png',
     'indecent-exposure': '71.png',
     'drug-heroin-sell': '72.png',
     'theft-stln-vehicle-trailer': '73.png',
     'harassment-dv': '74.png',
     'theft-purse-snatch-no-force': '75.png',
     'false-imprisonment': '76.png',
     'failure-to-appear': '77.png',
     'assault-police-simple': '78.png',
     'prostitution-engaging-in': '79.png',
     'burglary-poss-of-tools': '80.png',
     'property-crimes-other': '81.png',
     'burg-auto-theft-resd-no-force': '82.png',
     'robbery-bank': '83.png',
     'impersonation-of-police': '84.png',
     'fraud-criminal-impersonation': '85.png',
     'forgery-checks': '86.png',
     'drug-barbiturate-sell': '87.png',
     'drug-hallucinogen-sell': '88.png',
     'drug-marijuana-possess': '89.png',
     'robbery-car-jacking': '90.png',
     'sex-aslt-fondle-adult-victim': '91.png',
     'burglary-vending-machine': '92.png',
     'sex-off-fail-to-register': '93.png',
     'forgery-posses-forge-device': '94.png',
     'other-enviornment-animal-viol': '95.png',
     'harassment-sexual-in-nature': '96.png',
     'theft-from-mails': '97.png',
     'drug-marijuana-sell': '98.png',
     'fraud-by-use-of-computer': '99.png',
     'drug-marijuana-cultivation': '100.png',
     'drug-opium-or-deriv-sell': '101.png',
     'illegal-dumping': '102.png',
     'weapon-flourishing': '103.png',
     'animal-cruelty-to': '104.png',
     'arson-residence': '105.png',
     'burg-auto-theft-busn-no-force': '106.png',
     'bomb-threat': '107.png',
     'vehicular-eluding': '108.png',
     'police-obstruct-investigation': '109.png',
     'police-disobey-lawful-order': '110.png',
     'sex-aslt-non-rape': '111.png',
     'burg-auto-theft-busn-w-force': '112.png',
     'liquor-sell': '113.png',
     'intimidation-of-a-witness': '114.png',
     'fraud-by-telephone': '115.png',
     'drug-synth-narcotic-sell': '116.png',
     'kidnap-adult-victim': '117.png',
     'theft-of-rental-property': '118.png',
     'arson-vehicle': '119.png',
     'pawn-broker-viol': '120.png',
     'weapon-fire-into-occ-bldg': '121.png',
     'forgery-counterfeit-of-obj': '122.png',
     'liquor-misrepresent-age-minor': '123.png',
     'disarming-a-peace-officer': '124.png',
     'traf-vehicular-homicide': '125.png',
     'forgery-other': '126.png',
     'homicide-other': '127.png',
     'aslt-agg-police-gun': '128.png',
     'obstructing-govt-operation': '129.png',
     'harassment-stalking-dv': '130.png',
     'theft-fail-return-rent-veh': '131.png',
     'weapon-fire-into-occ-veh': '132.png',
     'theft-confidence-game': '133.png',
     'drug-hallucinogen-mfr': '134.png',
     'fraud-nsf-closed-account': '135.png',
     'robbery-purse-snatch-w-force': '136.png',
     'parole-violation': '137.png',
     'theft-embezzle': '138.png',
     'stolen-property-buy-sell-rec': '139.png',
     'extortion': '140.png',
     'escape': '141.png',
     'police-making-a-false-rpt': '142.png',
     'theft-stln-veh-const-eqpt': '143.png',
     'forgery-poss-of-forged-inst': '144.png',
     'drug-make-sell-other-drug': '145.png',
     'wiretapping': '146.png',
     'burglary-safe': '147.png',
     'arson-business': '148.png',
     'drug-hallucinogen-possess': '149.png',
     'drug-synth-narcotic-possess': '150.png',
     'violation-of-custody-order': '151.png',
     'drug-forgery-to-obtain': '152.png',
     'prostitution-pimping': '153.png',
     'drug-fraud-to-obtain': '154.png',
     'probation-violation': '155.png',
     'window-peeping': '156.png',
     'sex-aslt-w-object': '157.png',
     'sex-aslt-rape-pot': '158.png',
     'prostitution-aiding': '159.png',
     'sex-aslt-non-rape-pot': '160.png',
     'animal-poss-of-dangerous': '161.png',
     'traf-impound-vehicle': '162.png',
     'arson-public-building': '163.png',
     'homicide-family': '164.png',
     'fireworks-possession': '165.png',
     'bribery': '166.png',
     'forgery-poss-of-forged-ftd': '167.png',
     'explosive-incendiary-dev-pos': '168.png',
     'contraband-possession': '169.png',
     'loitering': '170.png',
     'drug-methamphetamine-mfr': '171.png',
     'obscene-material-possess': '172.png',
     'theft-gas-drive-off': '173.png',
     'escape-aiding': '174.png',
     'gambling-gaming-operation': '175.png',
     'sex-aslt-w-object-pot': '176.png',
     'altering-vin-number': '177.png',
     'gambling-device': '178.png',
     'explosive-incendiary-dev-use': '179.png',
     'homicide-police-by-gun': '180.png',
     'drug-barbiturate-possess': '181.png',
     'liquor-manufacturing': '182.png',
     'eavesdropping': '183.png',
     'liquor-other-viol': '184.png',
     'gambling-betting-wagering': '185.png',
     'pub-peace-desecrate-symb': '186.png',
     'sex-off-registration-viol': '187.png',
     'drug-barbiturate-mfr': '188.png',
     'obscene-material-mfr': '189.png',
     'homicide-negligent': '190.png',
     'riot': '191.png',
     'theft-from-yards': '192.png',
     'theft-of-cable-services': '193.png',
     'explosives-posses': '194.png',
     'homicide-solicitation': '195.png'}




    marker = []
    for i in x:
        #b = {'icon': icons[i[0]], 'lat': i[1], 'lng': i[2], 'infobox':'%s'%i[0]}
        b = {'icon': 'http://maps.google.com/mapfiles/ms/icons/yellow-dot.png', 'lat': i[1], 'lng': i[2],
             'infobox': '%s' % i[0]}
        marker.append(b)

    return a, marker